version: '3.8'

networks:
  apps-net:
    external: true

services:
  shared-proxy:
    image: nginx:alpine
    container_name: shared-nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - apps-net
