events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream fortinet_backend {
        server fortinet-app:5050;
    }

    upstream btc_backend {
        server trading-btc-app:5000;
    }

    server {
        listen 80;
        server_name _;

        # 🚀 Ruta para la App Fortinet: http://192.168.1.222/fortinet/
        location /fortinet/ {
            proxy_pass http://fortinet_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 🚀 Ruta para la App BTC: http://192.168.1.222/
        location / {
            proxy_pass http://btc_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
