version: '3.8'

networks:
  apps-net:
    external: true

services:
  fortinet-db:
    image: postgres:15-alpine
    container_name: fortinet-postgres
    restart: always
    environment:
      POSTGRES_DB: fortinet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - fortinet_postgres_data:/var/lib/postgresql/data
    networks:
      - apps-net

  fortinet-app:
    build: .
    container_name: fortinet-app
    restart: always
    depends_on:
      - fortinet-db
    environment:
      - DB_HOST=fortinet-postgres
      - DB_PORT=5432
      - DB_NAME=fortinet_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PYTHONPATH=/app
    ports:
      - "5050:5050"
    networks:
      - apps-net

volumes:
  fortinet_postgres_data:
