events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream fortinet_app {
        server app:5050;
    }

    server {
        listen 80;
        server_name _;

        # Acceso por sub-ruta http://192.168.1.222/fortinet/
        location /fortinet/ {
            proxy_pass http://fortinet_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Acceso por IP directa http://192.168.1.222/
        location / {
            proxy_pass http://fortinet_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
